# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7964e14bc7ff5629fe476f5ca38ba32fd3bb30a34561fdc76f9d1c1d6bd632b312c96f4440ed66cefc4da4d3dce6fe72da3eb288c50c3fb58e92b50c88c240cf

test:
  secret_key_base: bb3a1c0fe2caed79a806d3926e1e7f5b0f6da1195b584ff25d265aaed7551e26f4b459078a618f04ebbc0f154323b2c2c670175bdb91f0eecce35a285fb8fdfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
